function TitleSection(){
  return (
    <section class="text-center container">
      <div class="p-2 mb-2 bg-body-secondary text-end">18th June 2024</div>
      <h2 class="fw-light">Even Fibonacci Numbers</h2>
      <p class="lead text-body-secondary">
      Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1
      and 2, the first terms will be: <br/>1,2,3,5,8,13,21,34,55,89 ...
      <br/>
      By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
    </section>
  );
}

export default function Fibonacci(){
  var maxNumber = 4000000;

  var fibonacci = [1,2];
  var evenFibonacci = [1,2];
  while (fibonacci[fibonacci.length-1] < maxNumber){
    var newValue = fibonacci[fibonacci.length-1] + fibonacci[fibonacci.length-2];
    fibonacci.push(newValue);
    if(newValue % 2 === 0 && newValue < maxNumber){
      evenFibonacci.push(newValue);
    }
  }
  var sumEvenFibonacci = 0;
  for(var i = 0; i < evenFibonacci.length; i++){
    sumEvenFibonacci +=evenFibonacci[i];
  }

  return (
    <div>
      <TitleSection />
      <p className="text-break"><strong>Even numbers in the Fibonacci String:</strong> {evenFibonacci.toString()}</p>

      <p className="text-break"><strong>Sum of all the Even numbers in the Fibonacci String:</strong> {sumEvenFibonacci}</p>
    </div>
  );
}