function TitleSection(){
  return (
    <section class="text-center container">
      <div class="p-2 mb-2 bg-body-secondary text-end">18th June 2024</div>
      <h2 class="fw-light">Even Fibonacci Numbers</h2>
      <p class="lead text-body-secondary">
      Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1
      and 2, the first terms will be: <br/>1,2,3,5,8,13,21,34, 55,89 ...
      <br/>
      By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p>
    </section>
  );
}

export default function Fibonacci(){

  var fibonacci = [1,2,3,5,8,13,21,34];
  while (fibonacci[fibonacci.length-1] < 4000000){
    fibonacci.push(fibonacci[fibonacci.length-1] + fibonacci[fibonacci.length-2]);
  }
  //delete last item (over 4000000)
  fibonacci.pop();

  return (
    <div>
      <TitleSection />
      <p className="text-break">{fibonacci.toString()}</p>
    </div>
  );
}